### PR TITLE
Release Oct 28 2020

### PR DESCRIPTION
**Pull request by allburov**

### CODE REVIEW

**Comment by allburov** [comment]
@Tim55667757 Hi! 
We have a lot of unmerged changes, thanks to all contibutors and especcially to @dolfinus for about 10 PR :)

What do you think about release these changes on the next Wendsay, Oct 28?

**Comment by dolfinus** [comment]
Hello.

Any updates?

**Comment by allburov** [comment]
Deadlines are not about us :D

**Comment by dolfinus** [comment]
Thanks! :)

**Pull request merged**
