### PR TITLE
update and fix: New features: Token and list of objects #103

### PR DESCRIPTION
**Pull request by beliaev-maksim**

### CODE REVIEW

**Comment by beliaev-maksim** [comment]
@allburov , @Arlington1985 
I rebased the branch, merged it with develop and ran pre-commit. Please validate the functionality

**Comment by Arlington1985** [comment]
Hi Maksim. It seems ok for me. Thanks

**Comment by norpol** [comment]
I'm just a little bit unhappy that these commits basically copy paste my code, losing my commits entirely (and any credibility). I assume @Arlington1985 did this because unfamiliarity with git, but I'm a bit sad that my commits are lost now including loss of credits for me, never resolved discussion points on style questions and the remaining TODO in the code.

https://github.com/devopshq/artifactory/pull/21/commits

**Comment by beliaev-maksim** [comment]
@norpol 

I am sad to hear that. I just joined the project a while ago and did have a chance to see the full history. I did know that smth was cut by rebase of Arlington or in any other different way. I saw a good feature that was not finished, so I updated and rebase it to current state.

**Pull request merged**
