### PR TITLE
Add support for downloading artifact in chunks

### PR DESCRIPTION
**Pull request by andjelx**
To fix issue:
https://github.com/devopshq/artifactory/issues/135

### CODE REVIEW

**Review by allburov — CHANGES_REQUESTED** [review]
PR looks good for me. Could you add some examples to the README.md  and note how it is different from the `write`  https://github.com/devopshq/artifactory#downloading-artifacts

**Comment by andjelx** [comment]
> PR looks good for me. Could you add some examples to the README.md and note how it is different from the `write` https://github.com/devopshq/artifactory#downloading-artifacts

I have updated the examples. I can only guess why it help to resolve the issue with downloading YAML files - probably it's the way how Artifactory is streaming the files with such extensions and only using iter_content with stream=True makes download work properly.

**Comment by andjelx** [comment]
@allburov Gentle reminder, can you please have a second review look?

**Comment by allburov** [comment]
Thanks, appreciate your work!

**Comment by andjelx** [comment]
@allburov thanks. do you know next planned release date?

**Pull request merged**
