### PR TITLE
added new functionality to support API archive download

### PR DESCRIPTION
**Pull request by beliaev-maksim**
1. added new functionality to support API archive download
2. added example into README.md

### CODE REVIEW

**Comment by beliaev-maksim** [comment]
@allburov 
Hi Aleksey,
can you please have a look?
looks like build failed on readme.md

**Comment by allburov** [comment]
@beliaev-maksim hi! I'm so sorry, I had a mess in my email's inbox, and missed your PR.

Let's see. We use https://pre-commit.com/ to check that README.md table of content is up-to-date and to format python code to "black" standart. https://github.com/devopshq/artifactory/blob/master/docs/CONTRIBUTE.md#prepare-development-environment

You should follow these steps on your computer to fix failed CI:
- install pre-commit
- run `pre-commit run --all-files`
- commit and push the new changes

**Comment by beliaev-maksim** [comment]
@allburov 
it was a funny battle against CRLF endings since I am running on Windows machine :)

I recommend to add a hook for mixed endings to automatically replace them all to LF (Linux)

**Comment by allburov** [comment]
@beliaev-maksim Yes, there is this problem, sometimes. I've switched to linux about 1 year ago, so I don't encounter the problem anymore ;)

It'll be pleasant if someone who works on Windows create a PR.

**Comment by beliaev-maksim** [comment]
@allburov 
actually it is strange why precommit changes line endings at all, since git is smart enough to change them all to LF  when push and set CRLF on Windows during pull or LF on Linux

I will try to have a look at pre commit settings

**Pull request merged**
