### PR TITLE
stat: add .created, .last_updated, .last_modified to returned namedtuple

### PR DESCRIPTION
**Pull request by OddBloke**
This introduces access to `lastUpdated` in the return value, as well as adding `ctime` and `mtime` equivalents with the same naming scheme.

### CODE REVIEW

**Review by allburov — APPROVED** [review]

**Comment by beliaev-maksim** [comment]
Looks great, can you please add a deprecation notice for old attributes?

**Comment by allburov** [comment]
@beliaev-maksim Let's do not do it, it's the standard in other areas and we should keep those fields, it costs nothing to us

**Comment by beliaev-maksim** [comment]
@allburov
Then it is a confusion to have two fields that do the same. We either deprecate old implicit names or remove newly added

**Comment by OddBloke** [comment]
I've just pushed up updated docstrings, and replaced the one other usage of [cm]time in docs that I could find.

**Pull request merged**
