### PR TITLE
Release (15 Dec 2021)

### PR DESCRIPTION
**Pull request by allburov**
- [x] Approves from the core team (internal testing in their infrastructure)
- [x] Deploy release via Github Actions https://github.com/devopshq/artifactory/issues/308

### CODE REVIEW

**Comment by apazdnikov** [comment]
looks perfect. 
lets wait for tests from Sergey and Vasiliy

**Comment by beliaev-maksim** [comment]
that a big one :D

**Comment by TypeMayVary** [comment]
Any update on this merge?

**Review by vasokot — APPROVED** [review]

**Comment by allburov** [comment]
@vasokot @TypeMayVary @beliaev-maksim  
We're going to release it on 15 December!

**Review by sseuzss — APPROVED** [review]

**Comment by beliaev-maksim** [comment]
@allburov @vasokot @sseuzss 
and pipe works wonderful :)
I just tested it

image

**Comment by allburov** [comment]
@beliaev-maksim thank you for configuring this wonderful pipeline, we appreciate that!

**Pull request merged**
