### PR TITLE
Enhancement/add federated repo

### PR DESCRIPTION
**Pull request by RoeeDr**
Add a new repo type called "Federated" that inherits most of the functionality from RepositoryLocal

* Related to: https://github.com/devopshq/artifactory/issues/398

### CODE REVIEW

**Review by allburov — APPROVED** [review]

**Comment by RoeeDr** [comment]
@allburov The python 3.6 check is failing on all open PRs :( 
Do you have any idea what it is?

**Comment by allburov** [comment]
@RoeeDr 
We can skip python 3.6, it's too old and has no security updates. I've removed it https://github.com/devopshq/artifactory/pull/400

**Review by beliaev-maksim — APPROVED** [review]
looks good, thanks

**Comment by RoeeDr** [comment]
@beliaev-maksim @allburov 
Thanks for the review 🙏 
Would love for a merge and a version bump so I can close the issue in my end

**Pull request merged**
