### PR TITLE
Update artifactory.py

### LINKED ISSUE #88: The function splitroot() does not work for Cloud Enterprise artifactory repos
Our Cloud Enterprise repo name path is organized like this:

https://<Company_name>.jfrog.io/<Company_name>/

the function splitroot() in _ArtifactoryFlavour assumes the format:

http://mysite/artifactory

and attempts to parse based on /artifactory/
It was incorrectly parsed in my use case and I needed to hardcode <Company_name> in place of /artifactory/ 
To support more use cases, an option to pass in the "Drive" and "path" separately into the ArtifactoryPath constructor to bypass the parsing would be very nice

### PR DESCRIPTION
**Pull request by alanyee**
Treat the path after netloc to be part of the base URL

Fixes #88 and and #115 

`ArtifactoryPath` relies on `~/.artifactory_python.cfg` to first understand what the base url is, and if it cannot understand, it looks for `artifactory` assuming the URL looks like `<scheme://host_name/artifactory>` to separate out for parts of the url on what is the base url and what is the rest. The last resort is for `<scheme://host_name/path>` to simply treat `<scheme://host_name>` as the base url.

Given what I have seen and https://www.jfrog.com/confluence/display/RTF/Configuring+Apache#ConfiguringApache-ConfiguringaCustomURLBaseinArtifactory, I made the assumption that for something like `http://artifactory.yourdomain.com/repository/api/storage`, that `http://artifactory.yourdomain.com/repository` is the base url. Obviously, this fails some of the unit tests, but those unit tests are perhaps faulty based on the aforementioned assumptions. For my daily use, no errors have arisen from this fork.

My assumption is wrong if `http://artifactory.yourdomain.com/repository/artifact` can be the base url such that `http://artifactory.yourdomain.com/repository/artifact/api/security/users` exists, but I have not yet seen such an example.

### CODE REVIEW

**Comment by allburov** [comment]
@alanyee could you rebase your branch onto current develop?

**Comment by alanyee** [comment]
@allburov I rebased it.

**Comment by allburov** [comment]
@alanyee thank you! About failed tests - I'll look at them in this week and I will check this changes don't break work.

Let me be a meticulous reviewer, a little.

1. Commit should contains "atomic" changes.
For example, I am looking at these changes and can not quickly get changes  in the `get_base_url` function. In the pull request we have three unrelated changes: 
   1.`move get_base_url`
   2. `Add expicitly return None` 
   3.`Treat the path after netloc to be part of the URL: fix #88 fix #115`

We don't mind have more than one commit or feature changes in pull request, but review process must be as easy as it could be.Of course, I can copy-paste old and new `get_base_url` body to sublime and get diff, but I'm too lazy :)

2. Pass the issue number to a commit message.

**Comment by allburov** [comment]
It's hard to resolve this.

We have these type of "root":
1. `artifactory.example/artifactory/` - by default way to configure Artifactory
2. `artifactory.example/` - someone can configure her own reverse proxy for redirect to `artifactory.example/artifactory/`
3. `https://<Company_name>.jfrog.io/<Company_name>/` - SaaS solution

For the moment, library and it's tests supports **1,2** way. And we have workaround for **3**: `global_config` or the `~/artifactory.cfg` file.

If we make these changes, we will support **1,3** way, but have to use similar workaround for **2**.

Another way to fix #88 and and #115 - add explicit parameter to `ArtifactoryPath`
```python
# Work as expected in previous versions of library
# Base will determine automatically 
a = ArtifactoryPath("artifactory.example/artifactory/")
b = ArtifactoryPath("artifactory.example/")

# new way to pass base
c = ArtifactoryPath("https://<Company_name>.jfrog.io/<Company_name>/", base="https://<Company_name>.jfrog.io/<Company_name>/")
```

Without this I don't know how we can save compatibility

@alanyee what do you think? May be you see other problems with above method.

**Comment by alanyee** [comment]
@allburov I can go with that approach. I thought of it beforehand, but I went with this approach since I was unsure of how else the reverse proxy could look like.

**Comment by allburov** [comment]
I've rethinked this bugs, and suggest just add separate `ArtifactorySaaSPath` class. https://github.com/devopshq/artifactory/pull/128

May be in the future we can implement more inteligence way to detect base path we will have to just do `ArtifactorySaaSPath = ArtifactoryPath` to save compatibility in the future

**Comment by alanyee** [comment]
@allburov the other thought I had was that we could expose the `drive` or `root` since there is a hardcoded portion that simply checks for `"artifactory"`

**Pull request closed without merging**
